### PR TITLE
docs: Add repo link to metadata

### PR DESCRIPTION
**Pull request by ChristophWurst**
The link will show on https://apps.nextcloud.com/apps/uppush.

### CODE REVIEW

**Comment by p1gp1g** [comment]
Thanks, could you set https://codeberg.org/NextPush/uppush instead ? I can do it myself if you prefer

**Comment by ChristophWurst** [comment]
Feel free to push to my branch

**Comment by p1gp1g** [comment]
Hello. Why did you closed this PR ? I haven't had time to edit and merge it :)

**Comment by ChristophWurst** [comment]
There is only one line and it needs to change. It's easier to do the changes from scratch :)

**Comment by p1gp1g** [comment]
That's true, but seeing the PR help me to not forget haha

**Comment by p1gp1g** [comment]
Well, I've pushed it so it's done. Thanks :)

**Pull request closed without merging**
